# Generated by Django 5.1 on 2026-01-14 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adderss', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('PD', 'Pending'), ('DF', 'Delivered')], default='PD', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
